repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier

  - repo: https://github.com/psf/black
    rev: "23.9.1" # Use the latest stable version
    hooks:
      - id: black

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.7 # Use the latest stable version
    hooks:
      - id: sqlfluff-lint
        args: [--dialect=postgres] # Set your SQL dialect (e.g., postgres, bigquery, etc.)
      - id: sqlfluff-fix
        args: [--dialect=postgres]
