services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: .
      dockerfile: ./Dockerfile.airflow
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      AIRFLOW__CORE__AUTH_MANAGER: "airflow.api_fastapi.auth.managers.simple.simple_auth_manager.SimpleAuthManager"
      AIRFLOW__WEBSERVER__ENABLE_USER_REGISTRATION: "True"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_PASSWORDS_FILE: "/opt/airflow/simple_auth_manager_passwords.json"
      PYTHONPATH: /opt/airflow

    depends_on:
      - postgres
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db migrate && \
      mkdir -p /opt/airflow && \
      echo '{\"admin\": \"'${POSTGRES_PASSWORD}'\"}' > /opt/airflow/simple_auth_manager_passwords.json && \
      airflow api-server
      "

    ports:
      - "8080:8080"

    restart: on-failure
    volumes:
      - .:/opt/airflow

  airflow-scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile.airflow
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PYTHONPATH: /opt/airflow

    depends_on:
      - airflow-webserver
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db migrate && \
      airflow scheduler
      "
    ports:
      - "8081:8081"
    volumes:
      - .:/opt/airflow

  airflow-dag-processor:
    build:
      context: .
      dockerfile: ./Dockerfile.airflow
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PYTHONPATH: /opt/airflow

    depends_on:
      - airflow-scheduler
      - airflow-webserver

    entrypoint: /bin/bash
    command: >
      -c "
      airflow dag-processor
      "
    ports:
      - "8082:8082"
    volumes:
      - .:/opt/airflow

  airflow-triggerer:
    build:
      context: .
      dockerfile: ./Dockerfile.airflow
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      PYTHONPATH: /opt/airflow

    depends_on:
      - airflow-scheduler
      - airflow-webserver
      - airflow-dag-processor

    entrypoint: /bin/bash
    command: >
      -c "
      airflow triggerer
      "
    ports:
      - "8083:8083"
    volumes:
      - .:/opt/airflow

  spark:
    build:
      context: .
      dockerfile: ./Dockerfile.spark
    environment:
      - SPARK_MODE=master
    depends_on:
      - airflow-triggerer
    ports:
      - "8077:8077" # Spark UI
      - "7077:7077" # Spark master port

  spark-worker:
    build:
      context: .
      dockerfile: ./Dockerfile.spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark

  datapipeline:
    image: datapipeline
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - spark-worker
    ports:
      - "8000:8000"
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - SPARK_JARS=/opt/spark/jars/postgresql-42.7.3.jar
      - IS_MAIN_CONTAINER=true
    command:
      [
        "/bin/sh",
        "-c",
        "echo 'Container is running!'; while true; do sleep 1000; done",
      ]

volumes:
  pgdata:
