services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:3.0.1-python3.12
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    entrypoint: /bin/bash
    command: >
      -c "
      airflow db migrate && \
      airflow api-server 
      "

    ports:
      - "8080:8080"

    restart: on-failure

    volumes:
      - ./sql_scripts:/opt/airflow/sql_scripts
      - ./airflow:/opt/airflow/airflow_scripts

  airflow-scheduler:
    image: apache/airflow:3.0.1-python3.12
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - airflow-webserver
    entrypoint: /bin/bash
    command: >
      -c "
      airflow scheduler
      "
    ports:
      - "8081:8081"

  spark:
    build:
      context: .
      dockerfile: ./Dockerfile.spark
    environment:
      - SPARK_MODE=master
    depends_on:
      - airflow-scheduler
    ports:
      - "8077:8077" # Spark UI
      - "7077:7077" # Spark master port

  spark-worker:
    build:
      context: .
      dockerfile: ./Dockerfile.spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark

  datapipeline:
    image: datapipeline
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - spark-worker
    ports:
      - "8000:8000"
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - SPARK_JARS=/opt/spark/jars/postgresql-42.7.3.jar
    command:
      [
        "/bin/sh",
        "-c",
        "echo 'Container is running!'; while true; do sleep 1000; done",
      ]

volumes:
  pgdata:
