FROM bitnami/spark:3.5.1

USER root
RUN apt-get update && apt-get install -y wget

USER 1001

RUN mkdir -p /opt/bitnami/spark/jars && \
    wget -O /opt/bitnami/spark/jars/postgresql-42.7.3.jar https://jdbc.postgresql.org/download/postgresql-42.7.3.jar