FROM apache/airflow:3.0.1-python3.12

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt

USER root
RUN apt-get update && apt-get install -y wget

USER 1001

RUN apt-get update && apt-get install -y openjdk-17-jre-headless procps && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64

USER airflow